---
title: "Python in R Notebook"
output: html_notebook
---
<style>
#testpara {color: blue; width: 90px;}
</style>

<br>
I upgraded RStudio to the latest stable version (1.0.44), with its R Notebook authoring capability.

The ability to insert Python chunks and the Preview functionality, were of particular interest.

When a new R Notebook file is created the following information is given in the template:

<div style="width: 80%; padding-left: 50px; padding-right: 50px; color: blue; font-family: Comic Sans MS; font-size: 16px;">
When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
</div>

Using matplotlib and numpy, I inserted a simple plotting routine. The inline function, available in Jupyter notebooks is yet to be implemented, so the plot showed up in another window.


```{python}

import matplotlib.pyplot as plt
import numpy as np



t = np.arange(0.0, 2.0, 0.01)
s = np.sin(2*np.pi*t)
plt.plot(t, s)

plt.xlabel('time (s)')
plt.ylabel('voltage (mV)')
plt.title('About as simple as it gets, folks')
plt.grid(True)
plt.show()
```

I also had another plot, a histogram, following the plot above, I had to close the first plot window for the second one to be rendered.

```{python}

import matplotlib.pyplot as plt
import numpy as np


mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000)

# the histogram of the data
n, bins, patches = plt.hist(x, 50, normed=1, facecolor='g', alpha=0.75)


plt.xlabel('Smarts')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(60, .025, r'$\mu=100,\ \sigma=15$')
plt.axis([40, 160, 0, 0.03])
plt.grid(True)
plt.show()
```








